# Generated by Django 3.2.5 on 2022-05-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_alter_user_last_name'),
        ('users', '0003_user_is_verified'),
    ]

    operations = [
    ]
