# Generated by Django 4.0.4 on 2022-05-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_alter_user_last_name'),
        ('users', '0003_user_is_verified'),
    ]

    operations = [
    ]
