# Generated by Django 3.2.13 on 2022-05-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
