# Generated by Django 3.2.13 on 2022-05-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signaux', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signaux.categorie'),
        ),
    ]
