# Generated by Django 4.0.4 on 2022-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('RoleID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('RoleName', models.CharField(max_length=32, unique=True)),
                ('CreateAccount', models.BooleanField(default=False)),
                ('DesactivateAccount', models.BooleanField(default=False)),
                ('DeleteAccount', models.BooleanField(default=False)),
                ('ActivateAccount', models.BooleanField(default=False)),
                ('Addrole', models.BooleanField(default=False)),
                ('Editrole', models.BooleanField(default=False)),
                ('Deleterole', models.BooleanField(default=False)),
                ('EditCategory', models.BooleanField(default=False)),
                ('DeleteCategory', models.BooleanField(default=False)),
                ('AddCategory', models.BooleanField(default=False)),
            ],
        ),
    ]
