# Generated by Django 4.0.4 on 2022-05-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('RoleID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('RoleName', models.CharField(max_length=32, unique=True)),
                ('CreateAccount', models.BooleanField(default=False)),
                ('DesactivateAccount', models.BooleanField(default=False)),
                ('DeleteAccount', models.BooleanField(default=False)),
                ('ActivateAccount', models.BooleanField(default=False)),
                ('Addrole', models.BooleanField(default=False)),
                ('Editrole', models.BooleanField(default=False)),
                ('Deleterole', models.BooleanField(default=False)),
                ('EditCategory', models.BooleanField(default=False)),
                ('DeleteCategory', models.BooleanField(default=False)),
                ('AddCategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permissions')),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
