# Generated by Django 4.0.4 on 2022-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Roles',
        ),
    ]
