# Generated by Django 4.0.4 on 2022-05-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rename_user_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
