# Generated by Django 4.0.4 on 2022-05-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_rename_roles_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('RoleID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('RoleName', models.CharField(max_length=32, unique=True)),
                ('CreateAccount', models.BooleanField(default=False)),
                ('DesactivateAccount', models.BooleanField(default=False)),
                ('DeleteAccount', models.BooleanField(default=False)),
                ('ActivateAccount', models.BooleanField(default=False)),
                ('Addrole', models.BooleanField(default=False)),
                ('Editrole', models.BooleanField(default=False)),
                ('Deleterole', models.BooleanField(default=False)),
                ('EditCategory', models.BooleanField(default=False)),
                ('DeleteCategory', models.BooleanField(default=False)),
                ('AddCategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='ActivateAccount',
        ),
        migrations.RemoveField(
            model_name='role',
            name='AddCategory',
        ),
        migrations.RemoveField(
            model_name='role',
            name='Addrole',
        ),
        migrations.RemoveField(
            model_name='role',
            name='CreateAccount',
        ),
        migrations.RemoveField(
            model_name='role',
            name='DeleteAccount',
        ),
        migrations.RemoveField(
            model_name='role',
            name='DeleteCategory',
        ),
        migrations.RemoveField(
            model_name='role',
            name='Deleterole',
        ),
        migrations.RemoveField(
            model_name='role',
            name='DesactivateAccount',
        ),
        migrations.RemoveField(
            model_name='role',
            name='EditCategory',
        ),
        migrations.RemoveField(
            model_name='role',
            name='Editrole',
        ),
        migrations.RemoveField(
            model_name='role',
            name='RoleName',
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='RoleID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='roles.permissions'),
        ),
    ]
