# Generated by Django 4.0.4 on 2022-05-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_permissions_remove_role_activateaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
