# Generated by Django 4.0.4 on 2022-05-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permissions'),
        ),
    ]
